### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by sreevarsha** [xzhren/DeepForest#1]
Hi, 

I import the modeule as,

from gcforest.gcforest import GCForest

and it gives me an error, "ModuleNotFoundError: No module named 'gcforest' ".  I ran the requirements.txt with pip and that's all fine. Is there a setup file that I'm missing or something? Btw works perfectly in R. Please advise. Thanks !!

**Comment by kriselle** [comment]
Are you sure you're importing it in a file that's in the same folder as this gcforest library?

**Comment by kriselle** [comment]
How did you run the file? Have you tried following the steps in README.txt?

**Comment by xzhren** [comment]
The official implementation is https://github.com/kingfengji/gcForest, which can use this way to run.
This may be what you want to find.
My code is a updated version based on https://github.com/kingfengji/gcForest/tree/v1.0.

**Comment by sreevarsha** [comment]
Thanks everyone for your responses. I don't know what was happening, it was in the same directory and I read the readme file and all but still Python wasn't finding the function. But finally I made a setup.py and now it works. Thanks again !!!

**Comment by juvien** [comment]
can you share you setup.py file,please

**Comment by vamshi-299** [comment]
Hey ,Even I am facing the same issue can you please let me know how to resolve it
